# Generated by Django 5.0.6 on 2024-05-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
