# Generated by Django 5.0.6 on 2024-05-22 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image_url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
