# Generated by Django 5.0.6 on 2024-05-22 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
