# Generated by Django 5.0.6 on 2024-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
