# Generated by Django 5.0.6 on 2024-05-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(default="house chores", max_length=64),
            preserve_default=False,
        ),
    ]
