# Generated by Django 5.0.6 on 2024-05-23 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
