# Generated by Django 5.0.6 on 2024-05-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_bid_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_id",
                to="auctions.listing",
            ),
        ),
    ]
