# Generated by Django 5.0.6 on 2024-05-26 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="highest_bidder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
