# Generated by Django 5.0.6 on 2024-05-28 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
