# Generated by Django 5.0.6 on 2024-05-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_comment_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="listing",
            new_name="listing_id",
        ),
    ]
