# Generated by Django 5.0.6 on 2024-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_rename_listing_id_comment_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
